basePath: Workspace.xcworkspace

# Single test plan (for backwards compatibility)
testPlan: TestPlan.xctestplan

# Multiple test plans (recommended for processing multiple test plans)
# testPlans:
# - TestPlan1.xctestplan
# - TestPlan2.xctestplan

exclude:
- Fixtures
extra:
  targetsFiles:
    MyProjectName:SomeTarget:
    - Path/File.swift
    - Path/Subfolder
  dependencies:
    MyProjectName:SomeTarget:
    - MyProjectName:SecondTarget
    - Package:APackage
